---
- hosts: loggers
  sudo: yes

  vars_files:
   - vars/default.yml
  roles:
    - { role: rsyslog-server, tags: ["rsyslog-server"] }
    - { role: redis, tags: ["redis"] }
    - { role: elasticsearch, tags: ["elasticsearch"] }
    - { role: logstash, tags: ["logstash"] }
    - { role: apache-kibana, tags: ["apache-kibana"] }
