- name: Fetch Elasticsearch .rpm
  get_url: url={{ elurl }}-{{ ver }}.noarch.rpm dest=/tmp/elasticsearch-{{ ver }}.noarch.rpm

- name: Install Elasticsearch from .rpm
  yum:  name=/tmp/elasticsearch-{{ ver }}.noarch.rpm state=present
  notify:
   - restart elasticsearch
